{{- range .Values.serving.services }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- if .label }}
    {{- toYaml .label | nindent 4 }}
    {{- end }}
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: alquimia-env
---
{{- end }}