{{- range .Values.eventing.brokers }}
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: {{ .name }}
  annotations:
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: alquimia-evaluator
      uri: "{{ .deadLetterUri }}"
---
{{- end }}
