{{- range .Values.eventing.sequences }}
---
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: {{ .name }}
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
  steps:
    {{- range .steps }}
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: {{ .service }}
      uri: {{ .uri | quote }}
    {{- end }}
  {{- if .reply }}
  reply:
    ref:
      apiVersion: {{ .reply.apiVersion }}
      kind: {{ .reply.kind }}
      name: {{ .reply.name }}
  {{- end }}
{{- end }}
