{{- range .Values.eventing.triggers }}
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: {{ .name }}
spec:
  broker: {{ .broker }}
  {{- if .filter }}
  filter:
    attributes:
      {{- range $key, $value := .filter.attributes }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
  subscriber:
    ref:
      apiVersion: {{ .subscriber.apiVersion }}
      kind: {{ .subscriber.kind }}
      name: {{ .subscriber.name }}
{{- end }}
