{{- range $key, $service := .Values.services }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- if eq $key "leviathan" }}
    bindings.knative.dev/include: "true"
    {{- else }}
    app: entrypoint
    {{- end }}
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: {{ $service.image | default "quay.io/openshift-knative/showcase"}}
          name: {{ $service.name }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ $.Values.configuration.name }}
{{- end }}
